/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("com.diffplug.spotless") version "6.12.0"
    id("org.jetbrains.kotlin.jvm") version "1.8.10"
    id("org.jlleitschuh.gradle.ktlint") version "11.2.0"
    id("org.jetbrains.dokka") version "1.7.20"
    id("info.novatec.cbdg") version "2.0-SNAPSHOT"
}

repositories {
    mavenLocal()
    mavenCentral()
}

group = "info.novatec"
version = "1.0-SNAPSHOT"
description = "cbdg-gradle-test"
java.sourceCompatibility = JavaVersion.VERSION_17

dependencies {
    implementation("org.freemarker:freemarker:2.3.32")
    dokkaHtmlPlugin("org.jetbrains.dokka:kotlin-as-java-plugin:1.7.20")
}

tasks.named("build") {
    dependsOn("spotlessApply")
    dependsOn("generate")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "17"
    }
}

configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    kotlin {
        target("**/*.kt")
        ktlint()
    }
    kotlinGradle {
        target("*.gradle.kts")
        ktlint()
    }
}

// Configure the extension
// the<info.novatec.cbdg.plugin.CamundaBpmnDocumentationGeneratorConfiguration>().message.set("Hi from Gradle")
